import { useState, useEffect, useCallback } from "react";
import { invoke } from "@tauri-apps/api/core";
import { cn } from "@/lib/utils";
import { ArrowLeft, Layers, Trash2 } from "lucide-react";
import { A2uiSurfaceRenderer } from "./A2uiSurfaceRenderer";
import type { SavedA2uiPage } from "@/lib/launcherTypes";

interface A2uiTabPageProps {
	/** If set, directly show this page. Otherwise show the page list. */
	pageId?: string;
}

export function A2uiTabPage({ pageId }: A2uiTabPageProps) {
	const [pages, setPages] = useState<SavedA2uiPage[]>([]);
	const [selectedId, setSelectedId] = useState<string | null>(pageId ?? null);
	const [loading, setLoading] = useState(true);

	const loadPages = useCallback(async () => {
		try {
			const result = await invoke<SavedA2uiPage[]>("list_a2ui_pages");
			setPages(result);
		} catch (err) {
			console.error("[A2uiTabPage] failed to load pages:", err);
		} finally {
			setLoading(false);
		}
	}, []);

	useEffect(() => {
		void loadPages();
	}, [loadPages]);

	useEffect(() => {
		if (pageId) setSelectedId(pageId);
	}, [pageId]);

	const selectedPage = pages.find((p) => p.id === selectedId);

	const handleDelete = useCallback(
		async (id: string) => {
			try {
				await invoke("delete_a2ui_page", { pageId: id });
				setPages((prev) => prev.filter((p) => p.id !== id));
				if (selectedId === id) setSelectedId(null);
			} catch (err) {
				console.error("[A2uiTabPage] failed to delete page:", err);
			}
		},
		[selectedId],
	);

	if (loading) {
		return (
			<div className="flex items-center justify-center h-full text-muted-foreground/50 text-sm">
				Loading A2UI pages...
			</div>
		);
	}

	// Detail view
	if (selectedPage) {
		return (
			<div className="flex flex-col h-full">
				<div className="flex items-center gap-2 px-4 py-2.5 border-b border-border shrink-0">
					<button
						type="button"
						onClick={() => setSelectedId(null)}
						className="flex items-center gap-1 text-[13px] text-muted-foreground hover:text-foreground transition-colors"
					>
						<ArrowLeft className="w-4 h-4" />
						Back
					</button>
					<span className="text-[13px] font-medium text-foreground truncate">
						{selectedPage.title}
					</span>
					<button
						type="button"
						onClick={() => void handleDelete(selectedPage.id)}
						className="ml-auto p-1.5 rounded-md hover:bg-destructive/10 hover:text-destructive transition-all text-muted-foreground"
						title="Delete page"
					>
						<Trash2 className="w-3.5 h-3.5" />
					</button>
				</div>
				<div className="flex-1 overflow-hidden">
					<A2uiSurfaceRenderer messages={selectedPage.surfaceMessages} />
				</div>
			</div>
		);
	}

	// List view
	return (
		<div className="flex flex-col h-full">
			<div className="px-4 py-3 border-b border-border shrink-0">
				<h2 className="text-[15px] font-semibold text-foreground">
					Saved A2UI Pages
				</h2>
				<p className="text-[12px] text-muted-foreground/60 mt-0.5">
					Interactive pages generated by the agent
				</p>
			</div>
			<div className="flex-1 overflow-y-auto p-3">
				{pages.length === 0 ? (
					<div className="flex flex-col items-center justify-center h-full text-center">
						<Layers className="w-10 h-10 text-muted-foreground/20 mb-3" />
						<p className="text-[13px] text-muted-foreground/70 font-medium">
							No saved pages
						</p>
						<p className="text-[11px] text-muted-foreground/50 mt-1 max-w-[240px]">
							Ask the agent to create an interactive page, then save it for
							quick access.
						</p>
					</div>
				) : (
					<div className="space-y-1.5">
						{pages.map((page) => (
							<div
								key={page.id}
								className={cn(
									"group flex items-center gap-3 rounded-lg px-3 py-2.5 cursor-pointer transition-colors",
									"hover:bg-muted/60 active:bg-muted",
								)}
								onClick={() => setSelectedId(page.id)}
								onKeyDown={(e) => {
									if (e.key === "Enter" || e.key === " ") {
										setSelectedId(page.id);
									}
								}}
							>
								<div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
									<Layers className="w-4 h-4 text-primary" />
								</div>
								<div className="min-w-0 flex-1">
									<div className="text-[13px] font-medium text-foreground truncate">
										{page.title}
									</div>
									{page.description && (
										<div className="text-[11px] text-muted-foreground/60 truncate mt-0.5">
											{page.description}
										</div>
									)}
									<div className="text-[10px] text-muted-foreground/40 mt-0.5">
										{new Date(page.updatedAtMs).toLocaleDateString()}
									</div>
								</div>
								<button
									type="button"
									onClick={(e) => {
										e.stopPropagation();
										void handleDelete(page.id);
									}}
									className="opacity-0 group-hover:opacity-100 p-1.5 rounded-md hover:bg-destructive/10 hover:text-destructive transition-all"
									title="Delete page"
								>
									<Trash2 className="w-3.5 h-3.5" />
								</button>
							</div>
						))}
					</div>
				)}
			</div>
		</div>
	);
}
